apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::044211288591:role/fsndRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::044211288591:role/eksctl-jwt-api-cluster-nodegroup-NodeInstanceRole-150D502MJGG94
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-01-12T14:59:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1285"
  uid: de73f22d-88e7-42c7-a216-ce0167741dce
